name: WSJ Cron

on:
  schedule:
    - cron: "55 0,2,4,6,8 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: node noop.js
      env:
        GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
        GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
        GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
        LARK_APP_ID: ${{ secrets.LARK_APP_ID }}
        LARK_APP_SECRET: ${{ secrets.LARK_APP_SECRET }}
        LARK_USER: ${{ secrets.LARK_USER }}
        RSS_HOST: ${{ secrets.RSS_HOST }}
